language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - mvn clean

before_script:
  - mysql -e "create database IF NOT EXISTS JUserManagement;" -uroot

script:
  - mysql JUserManagement < src/main/resources/JUserManagement.sql -uroot
  - mvn test
 
after_success:
  - mvn clean cobertura:cobertura coveralls:report
